### ISSUE TITLE
Using dotted notes in TimeBase

### ISSUE THREAD

**Issue by Gimly** [Tonejs/Tone.js#372]
According to the wiki, we should be able to  add a "." to a notation to specify a dotted note, like "8n." for an dotted-eigth note, but when I try to use it in Time.add or pass it to a TimeBase, I get an exception that says:

```javascript
Tone.TimeBase("8n.");
```
```
SyntaxError: Tone.TimeBase: Unexpected token .
    at getNextToken (http://localhost:8100/build/vendor.js:110566:20)
    at Tone.TimeBase._tokenize (http://localhost:8100/build/vendor.js:110539:26)
    at Tone.TimeBase._parseExprString (http://localhost:8100/build/vendor.js:110679:27)
    at Tone.TimeBase.set (http://localhost:8100/build/vendor.js:110370:28)
    at new Tone.TimeBase (http://localhost:8100/build/vendor.js:110353:23)
    at Function.Tone.TimeBase (http://localhost:8100/build/vendor.js:110359:21)
    at http://localhost:8100/build/main.js:258:79
    at Array.forEach (<anonymous>)
    at TonePage.webpackJsonp.100.TonePage.setupPart (http://localhost:8100/build/main.js:246:20)
    at TonePage.webpackJsonp.100.TonePage.toggleDot (http://localhost:8100/build/main.js:106:14)
```

Is there something I'm missing?

**Comment by Gimly** [comment]
Looks like I was simply using an old version, it's fixed with the latest from npm.
