### ISSUE TITLE
Error when running tests on a clean clone on the typescript branch

### ISSUE THREAD

**Issue by jcapinc** [Tonejs/Tone.js#545]
Bugs and feature requests only please.

For help questions, check out the forum: https://groups.google.com/forum/#!forum/tonejs

If possible, please include a link which illustrates the issue.

https://jsfiddle.net/1f60jkq4/ (tone@latest)
https://jsfiddle.net/z9marxbt/ (tone@next)

Clone branch, checkout `typescript`, run `npm run test`. 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'karma' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prekarma', 'karma', 'postkarma' ]
5 info lifecycle tone@14.3.0~prekarma: tone@14.3.0
6 info lifecycle tone@14.3.0~karma: tone@14.3.0
7 verbose lifecycle tone@14.3.0~karma: unsafe-perm in lifecycle true
8 verbose lifecycle tone@14.3.0~karma: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jeffs\projects\Tone.js\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jeffs\projects\Tone.js\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\jeffs\AppData\Local\Microsoft\WindowsApps;C:\Users\jeffs\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\jeffs\AppData\Roaming\npm;C:\Program Files\Git\mingw64\bin;
9 verbose lifecycle tone@14.3.0~karma: CWD: C:\Users\jeffs\projects\Tone.js
10 silly lifecycle tone@14.3.0~karma: Args: [ '/d /s /c',
10 silly lifecycle   'karma start scripts/karma.conf.js --single-run --file $npm_config_file --dir $npm_config_dir' ]
11 silly lifecycle tone@14.3.0~karma: Returned: code: 1  signal: null
12 info lifecycle tone@14.3.0~karma: Failed to exec karma script
13 verbose stack Error: tone@14.3.0 karma: `karma start scripts/karma.conf.js --single-run --file $npm_config_file --dir $npm_config_dir`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid tone@14.3.0
15 verbose cwd C:\Users\jeffs\projects\Tone.js
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "karma"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error tone@14.3.0 karma: `karma start scripts/karma.conf.js --single-run --file $npm_config_file --dir $npm_config_dir`
22 error Exit status 1
23 error Failed at the tone@14.3.0 karma script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Is there some other setup other than `npm install` that I need to run tests? I want to contribute but I cannot get started.

**Comment by tambien** [comment]
I just tried this myself and wasn't able to reproduce this error

my steps:
```
git clone https://github.com/Tonejs/Tone.js.git
cd Tone.js
git checkout typescript
npm install
npm run test
```

All the tests ran fine for me. Is anyone else able to reproduce this error?

**Comment by jcapinc** [comment]
Important detail that I left out, I am on windows, I was trying out some of the other commands and noticed RM was used in at least one place, which did not work when I was using it.

Screenshot:
![image](https://user-images.githubusercontent.com/1325626/65548420-697c2280-dee9-11e9-8352-b96a273d0a86.png)

Text paste from screenshot:
```
PS C:\Users\jeffs\projects\empty> git clone https://github.com/Tonejs/Tone.js.git
Cloning into 'Tone.js'...
remote: Enumerating objects: 1243, done.
remote: Counting objects: 100% (1243/1243), done.
remote: Compressing objects: 100% (587/587), done.
Receiving objects: 100% (29786), reused 915 (delta 656), pack-reused 28543 eceiving objects: 100% (29786/29786), 20.60 MiB | 8.23 MiB/s
/29786), 23.04 MiB | 8.18 MiB/s, done.
Resolving deltas: 100% (22383/22383), done.
PS C:\Users\jeffs\projects\empty> cd .\Tone.js\
PS C:\Users\jeffs\projects\empty\Tone.js> git checkout typescript
Switched to a new branch 'typescript'
Branch 'typescript' set up to track remote branch 'typescript' from 'origin'.
PS C:\Users\jeffs\projects\empty\Tone.js> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1031 packages from 1812 contributors and audited 8010 packages in 197.215s
found 5 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\jeffs\projects\empty\Tone.js> npm run test

> tone@14.3.0 test C:\Users\jeffs\projects\empty\Tone.js
> npm run karma


> tone@14.3.0 karma C:\Users\jeffs\projects\empty\Tone.js
> karma start scripts/karma.conf.js --single-run --file $npm_config_file --dir $npm_config_dir

testing file "$npm_config_file"
24 09 2019 16:34:48.594:ERROR [launcher]: Cannot start Firefox
        *** You are running in headless mode.

24 09 2019 16:34:48.601:ERROR [launcher]: Firefox stdout:
24 09 2019 16:34:48.602:ERROR [launcher]: Firefox stderr: *** You are running in headless mode.

Firefox 69.0.0 (Windows 10.0.0): Executed 0 of 0 ERROR (0.16 secs / 0 secs)
HeadlessChrome 76.0.3809 (Windows 10.0.0): Executed 0 of 0 ERROR (0.141 secs / 0 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tone@14.3.0 karma: `karma start scripts/karma.conf.js --single-run --file $npm_config_file --dir $npm_config_dir`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tone@14.3.0 karma script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jeffs\AppData\Roaming\npm-cache\_logs\2019-09-24T20_35_22_851Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tone@14.3.0 test: `npm run karma`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tone@14.3.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jeffs\AppData\Roaming\npm-cache\_logs\2019-09-24T20_35_22_918Z-debug.log
PS C:\Users\jeffs\projects\empty\Tone.js>
```

**Comment by tambien** [comment]
Does it work in a windows terminal which supports unix commands like PowerShell?

**Comment by tambien** [comment]
This specific error looks like you might not have firefox installed?

**Comment by VishalBheda** [comment]
windows10
installed Firefox 69.0.1 
```
git clone https://github.com/Tonejs/Tone.js.git
cd Tone.js
git checkout typescript
npm install
npm run test
```

![image](https://user-images.githubusercontent.com/18244052/65711600-db539800-e0b2-11e9-87a3-b25014a8e3ae.png)

```
> tone@14.4.0 karma D:\New folder\Tone.js
> karma start scripts/karma.conf.js --single-run --file $npm_config_file --dir $npm_config_dir

testing file "$npm_config_file"
HeadlessChrome 77.0.3865 (Windows 10.0.0): Executed 0 of 0 ERROR (0.36 secs / 0 secs)
Firefox 69.0.0 (Windows 10.0.0): Executed 0 of 0 ERROR (0.265 secs / 0 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tone@14.4.0 karma: `karma start scripts/karma.conf.js --single-run --file $npm_config_file --d
r`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tone@14.4.0 karma script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hp Elitebook\AppData\Roaming\npm-cache\_logs\2019-09-26T17_33_20_898Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tone@14.4.0 test: `npm run karma`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tone@14.4.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hp Elitebook\AppData\Roaming\npm-cache\_logs\2019-09-26T17_33_20_950Z-debug.log
```

**Comment by tambien** [comment]
I'm seeing that it's trying to run the test directory "$npm_config_dir". That value is supposed to be undefined which causes it to run all of the tests. I wonder if it's related to this [SO answer](https://stackoverflow.com/questions/15536872/nodejs-npm-global-config-missing-on-windows)

If you try to explicitly set the directory does it work: `npm run test --dir=core` for example to test the 'core' directory.

**Comment by tambien** [comment]
accidentally hit "close"

**Comment by jcapinc** [comment]
I tried your command and got the same result. You can close this ticket if you want, don't waste too much time on it unless you really want to spend time on it.

**Comment by tambien** [comment]
@jcapinc I am curious why the tests won't run on Windows. I only run the tests on Mac and Linux so i don't have a good way to reproduce and debug this error. if you have time to look it, i'd greatly appreciate trying to figure out how to run these tests on windows. then we can update the documentation or the scripts to reflect that.

**Comment by tambien** [comment]
I found this: https://stackoverflow.com/questions/42166632/how-to-use-npm-config-variables-cross-platform-win-linux

**Comment by tambien** [comment]
@jcapinc were you able to get this to work on windows with the cross-vars added?

**Comment by jcapinc** [comment]
So I was not able to get it working, but I think you might be right about the problem and I am going to take some time to experiment with the NPM run commands and see if I can fix it myself, I will get back to you with what I find.

**Comment by jcapinc** [comment]
Alright, so after doing some experimenting, I am confused as to where these variables come from. where does `$npm_config_file` come from?

**Comment by tambien** [comment]
This enables you to set some flags from the command line. So for example you can test just the Oscillator file by doing something like `npm run test --file=Oscillator`

here's the docs for [npm config](https://docs.npmjs.com/misc/config)

**Comment by jcapinc** [comment]
![image](https://user-images.githubusercontent.com/1325626/66962117-3cc9af80-f03e-11e9-8545-ff9cfce4236f.png)

Success! Alright, I think I am starting to understand this, I can work with this. Thank you for the help.

**Comment by tambien** [comment]
glad it works! what did you do to get it working in the end? it'd be great to document it here for other people who might come across a similar issue.
