### ISSUE TITLE
Unable to compile after upgrade

### ISSUE THREAD

**Issue by raphaelbastide** [Tonejs/Tone.js#830]
After updating the tone package from `0.8.0` to `14.8.3`, I get this error:
```
ERROR in ./~/tone/build/Tone.js
Module parse failed: /home/…/project/node_modules/tone/build/Tone.js Unexpected token (1:16275)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:16275)
    at Parser.pp$4.raise (/home/…/project/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/…/project/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/home/…/project/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$1.parseTryStatement (/home/…/project/node_modules/acorn/dist/acorn.js:902:12)
    at Parser.pp$1.parseStatement (/home/…/project/node_modules/acorn/dist/acorn.js:702:31)
    at Parser.pp$1.parseBlock (/home/…/project/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/home/…/project/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$3.parseArrowExpression (/home/…/project/node_modules/acorn/dist/acorn.js:2087:10)
    at Parser.pp$3.parseExprAtom (/home/…/project/node_modules/acorn/dist/acorn.js:1776:21)
    at Parser.pp$3.parseExprSubscripts (/home/…/project/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/…/project/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/…/project/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/…/project/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/…/project/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/home/…/project/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/home/…/project/node_modules/acorn/dist/acorn.js:1796:19)
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 23:7-22

```
It appears to be a big version gap, did I skip a breaking change?

**Comment by vibertthio** [comment]
It's a big version gap indeed. Could you provide a way to reproduce your issue ([like this](https://github.com/Tonejs/Tone.js/blob/dev/.github/ISSUE_TEMPLATE.md)) or your source code? It seems that you are importing the whole Tone.js into your Vue project but it's really hard to tell where the issue is.

**Comment by stephendwolff** [comment]
@vibertthio i don't think this is me, i don't remember using Vue with Tone.js. Last time i just used it in a pretty vanilla js project. maybe @raphaelbastide will know more?

**Comment by raphaelbastide** [comment]
Yes it’s me! My code is [here](https://gitlab.com/raphaelbastide/grovity) and to reproduce the bug, you just have to change [this line](https://gitlab.com/raphaelbastide/grovity/-/blob/master/package.json#L18) to `"tone": "^14.7.77" before `npm install`. Thank you for your help @vibertthio.

**Comment by vibertthio** [comment]
@stephendwolff  Sorry about the confusion! I just typed the wrong name.

@raphaelbastide I took a look at your project. It's that your babel is too old for the "try and catch" syntax in the JavaScript syntax, so it's not a bug of Tone. The easiest way to solve it is to include the latest Tone.js in your `index.html` like this and remove the `require('tone')` in all your files using Tone. Your code can then access the global `Tone`.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="/assets/favicon.svg">
    <title>Grovity</title>
    <script src="https://unpkg.com/tone@latest/build/Tone.js"></script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>

```

**Comment by raphaelbastide** [comment]
Thank you, it works this way. I would be interested to know more about how to solve the babel issue. Can’t I just update babel? I would ideally want my project to be independent to any CDN. My issue is solved.
