### ISSUE TITLE
TypeError: Tone.Synth is not a constructor

### ISSUE THREAD

**Issue by SoulFireMage** [Tonejs/Tone.js#969]
I get the following error from the code I've included further down:

```
file:///C:/JavascriptCourse/sketches/hello.js:17
    const synth = new Tone.Synth().toDestination();
                  ^

TypeError: Tone.Synth is not a constructor
    at makeNoise (file:///C:/JavascriptCourse/sketches/hello.js:17:19)
    at Server.<anonymous> (file:///C:/JavascriptCourse/sketches/hello.js:12:3)
    at Server.emit (events.js:400:28)
    at parserOnIncoming (_http_server.js:900:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
```
I did install Typescript and run tsc --init just in case it was that. Sadly, I think it's not related. Unfortunately the examples do not go into enough depth for me to get this started on node. I looked at the source file and can see a constructor. So, I'm simply stuck and unable to explore the software. 

Is this a very simple common issue that I just haven't found the right google phrases to find the answer to? 
Thank you!

``` 
import * as Tone from 'tone'
import http from 'http';
 
const host = '0.0.0.0';
const port = 3000;
 
const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Tone is supposed to work here');
  makeNoise();
});
 
 
let  makeNoise =()=>{
    const synth = new Tone.Synth().toDestination();
    //play a middle 'C' for the duration of an 8th note
    synth.triggerAttackRelease("C4", "8n");
}

server.listen(port, host, () => {
   console.log('Web server running at http://%s:%s',host,port );
}); ```

**Comment by RCThales** [comment]
@tambien I get the same issue when trying to use it with NEXT.js 13 on a client component... Do you know what it could be?
